apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-config
  namespace: app-team-2
spec:
  destination:
    namespace: alpha-app-prod
    server: https://kubernetes.default.svc
  info:
    - name: GitHub Repo
      value: https://github.com/loft-demos/alpha-app/
  project: loft-auth-core
  source:
    path: vcluster-use-cases/argocd-vcluster-add-ons/manifests/prod/
    repoURL: https://github.com/loft-demos/alpha-app.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
