name: test-access-key

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: Show vCluster Version
        run: vcluster --version
      - name: Login to vCluster Platform instance
        env:
          VCLUSTER_PLATFORM_URL: ${{ vars.VCLUSTER_PLATFORM_URL }}
          ACCESS_KEY: ${{ secrets.VCLUSTER_PLATFORM_ACCESS_KEY }}
        run: vcluster platform login $VCLUSTER_PLATFORM_URL --access-key $ACCESS_KEY
